// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://myixipqnxdovqizilipm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15aXhpcHFueGRvdnFpemlsaXBtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MDI0OTEsImV4cCI6MjA2ODQ3ODQ5MX0.X7Y-_o-lxa9jDwjDyKKItaV0Tzz9swFnqX8qoErZYz4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});